package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.model.Appointment;

public class AppointmentDAO {

  public void save(Appointment appointment) {

    String sql =
        """
          INSERT INTO appointments (
            patient_id,
            service_id,
            doctor_id,
            appointment_date,
            appointment_time,
            status
          )
          VALUES (?, ?, ?, ?, ?, ?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

      statement.setInt(1, appointment.getPatientId());
      statement.setInt(2, appointment.getServiceId());

      // doctor_id
      if (appointment.getDoctorId() != null) {
        statement.setInt(3, appointment.getDoctorId());
      } else {
        statement.setNull(3, java.sql.Types.INTEGER);
      }

      statement.setString(4, appointment.getAppointmentDate().toString());
      statement.setString(5, appointment.getAppointmentTime().toString());
      statement.setString(6, appointment.getStatus());

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          appointment.setAppointmentId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Appointment findById(int appointmentId) {

    String sql =
        """
          SELECT *
          FROM appointments
          WHERE appointment_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, appointmentId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapAppointment(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public List<Appointment> findAll() {

    String sql =
        """
          SELECT *
          FROM appointments
        """;

    List<Appointment> appointments = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        appointments.add(mapAppointment(resultSet));
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return appointments;
  }

  public List<Appointment> findByPatient(int patientId) {

    String sql =
        """
          SELECT *
          FROM appointments
          WHERE patient_id = ?
        """;

    List<Appointment> appointments = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, patientId);

      try (ResultSet resultSet = statement.executeQuery()) {

        while (resultSet.next()) {
          appointments.add(mapAppointment(resultSet));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return appointments;
  }

  public void update(Appointment appointment) {

    String sql =
        """
          UPDATE appointments
          SET patient_id = ?,
              service_id = ?,
              doctor_id = ?,
              appointment_date = ?,
              appointment_time = ?,
              status = ?
          WHERE appointment_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, appointment.getPatientId());
      statement.setInt(2, appointment.getServiceId());

      // doctor_id
      if (appointment.getDoctorId() != null) {
        statement.setInt(3, appointment.getDoctorId());
      } else {
        statement.setNull(3, java.sql.Types.INTEGER);
      }

      statement.setString(4, appointment.getAppointmentDate().toString());
      statement.setString(5, appointment.getAppointmentTime().toString());
      statement.setString(6, appointment.getStatus());
      statement.setInt(7, appointment.getAppointmentId());

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public void delete(int appointmentId) {

    String sql =
        """
          DELETE FROM appointments
          WHERE appointment_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, appointmentId);

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  private Appointment mapAppointment(ResultSet resultSet) throws SQLException {

    Appointment appointment = new Appointment();

    appointment.setAppointmentId(resultSet.getInt("appointment_id"));

    appointment.setPatientId(resultSet.getInt("patient_id"));

    appointment.setServiceId(resultSet.getInt("service_id"));

    appointment.setDoctorId((Integer) resultSet.getObject("doctor_id"));

    appointment.setAppointmentDate(java.time.LocalDate.parse(resultSet.getString("appointment_date")));

    appointment.setAppointmentTime(java.time.LocalTime.parse(resultSet.getString("appointment_time")));

    appointment.setStatus(resultSet.getString("status"));

    String createdAt = resultSet.getString("created_at");

    if (createdAt != null) {
      appointment.setCreatedAt(java.time.LocalDateTime.parse(createdAt.replace(" ", "T")));
    }

    return appointment;
  }
}
