package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.model.Counter;

public class CounterDAO {

  public void save(Counter counter) {

    String sql =
        """
          INSERT INTO counters (
            department_id,
            counter_name,
            room_name,
            is_active
          )
          VALUES (?, ?, ?, ?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

      statement.setInt(1, counter.getDepartmentId());
      statement.setString(2, counter.getCounterName());
      statement.setString(3, counter.getRoomName());
      statement.setInt(4, counter.isActive() ? 1 : 0);

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          counter.setCounterId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Counter findById(int counterId) {

    String sql =
        """
          SELECT *
          FROM counters
          WHERE counter_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, counterId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapCounter(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public List<Counter> findAll() {

    String sql =
        """
          SELECT *
          FROM counters
        """;

    List<Counter> counters = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        counters.add(mapCounter(resultSet));
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return counters;
  }

  public List<Counter> findByDepartment(int departmentId) {

    String sql =
        """
          SELECT *
          FROM counters
          WHERE department_id = ?
        """;

    List<Counter> counters = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, departmentId);

      try (ResultSet resultSet = statement.executeQuery()) {

        while (resultSet.next()) {
          counters.add(mapCounter(resultSet));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return counters;
  }

  public void update(Counter counter) {

    String sql =
        """
          UPDATE counters
          SET department_id = ?,
              counter_name = ?,
              room_name = ?,
              is_active = ?
          WHERE counter_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, counter.getDepartmentId());
      statement.setString(2, counter.getCounterName());
      statement.setString(3, counter.getRoomName());
      statement.setInt(4, counter.isActive() ? 1 : 0);
      statement.setInt(5, counter.getCounterId());

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public void delete(int counterId) {

    String sql =
        """
          DELETE FROM counters
          WHERE counter_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, counterId);

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  private Counter mapCounter(ResultSet resultSet) throws SQLException {

    Counter counter = new Counter();

    counter.setCounterId(resultSet.getInt("counter_id"));

    counter.setDepartmentId(resultSet.getInt("department_id"));

    counter.setCounterName(resultSet.getString("counter_name"));

    counter.setRoomName(resultSet.getString("room_name"));

    counter.setActive(resultSet.getInt("is_active") == 1);

    return counter;
  }
}
