package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.database.DatabaseException;
import org.hospitalqueing.model.Doctor;

public class DoctorDAO {

  public void save(Doctor doctor) {

    String sql =
        """
          INSERT INTO doctors (
            user_id,
            department_id,
            first_name,
            last_name,
            license_number,
            is_active
          )
          VALUES (?, ?, ?, ?, ?, ?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

      statement.setInt(1, doctor.getUserId());
      statement.setInt(2, doctor.getDepartmentId());
      statement.setString(3, doctor.getFirstName());
      statement.setString(4, doctor.getLastName());
      statement.setString(5, doctor.getLicenseNum());
      statement.setInt(6, doctor.isActive() ? 1 : 0);

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          doctor.setDoctorId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }

  public Doctor findById(int doctorId) {

    String sql =
        """
          SELECT *
          FROM doctors
          WHERE doctor_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, doctorId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapDoctor(resultSet);
        }
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }

    return null;
  }

  public List<Doctor> findAll() {

    String sql =
        """
          SELECT *
          FROM doctors
        """;

    List<Doctor> doctors = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        doctors.add(mapDoctor(resultSet));
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }

    return doctors;
  }

  /** The doctor linked to a login account, or null. Mirrors StaffDAO.findByUser. */
  public Doctor findByUser(int userId) {

    String sql =
        """
          SELECT *
          FROM doctors
          WHERE user_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, userId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapDoctor(resultSet);
        }
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }

    return null;
  }

  public List<Doctor> findByDepartment(int departmentId) {

    String sql =
        """
          SELECT *
          FROM doctors
          WHERE department_id = ?
        """;

    List<Doctor> doctors = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, departmentId);

      try (ResultSet resultSet = statement.executeQuery()) {

        while (resultSet.next()) {
          doctors.add(mapDoctor(resultSet));
        }
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }

    return doctors;
  }

  public void update(Doctor doctor) {

    String sql =
        """
          UPDATE doctors
          SET user_id = ?,
              department_id = ?,
              first_name = ?,
              last_name = ?,
              license_number = ?,
              is_active = ?
          WHERE doctor_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, doctor.getUserId());
      statement.setInt(2, doctor.getDepartmentId());
      statement.setString(3, doctor.getFirstName());
      statement.setString(4, doctor.getLastName());
      statement.setString(5, doctor.getLicenseNum());
      statement.setInt(6, doctor.isActive() ? 1 : 0);
      statement.setInt(7, doctor.getDoctorId());

      statement.executeUpdate();

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }

  public void delete(int doctorId) {

    String sql =
        """
          DELETE FROM doctors
          WHERE doctor_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, doctorId);

      statement.executeUpdate();

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }

  private Doctor mapDoctor(ResultSet resultSet) throws SQLException {

    Doctor doctor = new Doctor();

    doctor.setDoctorId(resultSet.getInt("doctor_id"));

    // user_id arrives from the DOCTOR-role migration; guard so pre-migration DBs can't break reads.
    int userCol = resultSet.findColumn("user_id");
    doctor.setUserId(userCol == 0 ? 0 : resultSet.getInt(userCol));

    doctor.setDepartmentId(resultSet.getInt("department_id"));

    doctor.setFirstName(resultSet.getString("first_name"));

    doctor.setLastName(resultSet.getString("last_name"));

    doctor.setLicenseNum(resultSet.getString("license_number"));

    doctor.setActive(resultSet.getInt("is_active") == 1);

    return doctor;
  }
}
