package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.model.Feedback;

public class FeedbackDAO {

  public void save(Feedback feedback) {

    String sql =
        """
          INSERT INTO feedback (
            queue_id,
            patient_id,
            rating,
            comment
          )
          VALUES (?, ?, ?, ?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

      statement.setInt(1, feedback.getQueueId());
      statement.setInt(2, feedback.getPatientId());
      statement.setInt(3, feedback.getRating());
      statement.setString(4, feedback.getComment());

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          feedback.setFeedbackId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Feedback findById(int feedbackId) {

    String sql =
        """
          SELECT *
          FROM feedback
          WHERE feedback_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, feedbackId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapFeedback(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public List<Feedback> findAll() {

    String sql =
        """
          SELECT *
          FROM feedback
        """;

    List<Feedback> feedbackList = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        feedbackList.add(mapFeedback(resultSet));
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return feedbackList;
  }

  public List<Feedback> findByQueue(int queueId) {

    String sql =
        """
          SELECT *
          FROM feedback
          WHERE queue_id = ?
        """;

    List<Feedback> feedbackList = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, queueId);

      try (ResultSet resultSet = statement.executeQuery()) {

        while (resultSet.next()) {
          feedbackList.add(mapFeedback(resultSet));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return feedbackList;
  }

  public List<Feedback> findByPatient(int patientId) {

    String sql =
        """
          SELECT *
          FROM feedback
          WHERE patient_id = ?
        """;

    List<Feedback> feedbackList = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, patientId);

      try (ResultSet resultSet = statement.executeQuery()) {

        while (resultSet.next()) {
          feedbackList.add(mapFeedback(resultSet));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return feedbackList;
  }

  public void update(Feedback feedback) {

    String sql =
        """
          UPDATE feedback
          SET queue_id = ?,
              patient_id = ?,
              rating = ?,
              comment = ?
          WHERE feedback_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, feedback.getQueueId());
      statement.setInt(2, feedback.getPatientId());
      statement.setInt(3, feedback.getRating());
      statement.setString(4, feedback.getComment());
      statement.setInt(5, feedback.getFeedbackId());

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public void delete(int feedbackId) {

    String sql =
        """
          DELETE FROM feedback
          WHERE feedback_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, feedbackId);

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  private Feedback mapFeedback(ResultSet resultSet) throws SQLException {

    Feedback feedback = new Feedback();

    feedback.setFeedbackId(resultSet.getInt("feedback_id"));

    feedback.setQueueId(resultSet.getInt("queue_id"));

    feedback.setPatientId(resultSet.getInt("patient_id"));

    feedback.setRating(resultSet.getInt("rating"));

    feedback.setComment(resultSet.getString("comment"));

    String createdAt = resultSet.getString("created_at");

    if (createdAt != null) {
      feedback.setCreatedAt(java.time.LocalDateTime.parse(createdAt.replace(" ", "T")));
    }

    return feedback;
  }
}
