package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.model.Notification;

public class NotificationDAO {

  public void save(Notification notification) {

    String sql =
        """
          INSERT INTO notifications (
            patient_id,
            queue_id,
            channel,
            message,
            status,
            sent_at
          )
          VALUES (?, ?, ?, ?, ?, ?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

      statement.setInt(1, notification.getPatientId());

      // queue_id
      if (notification.getQueueId() != null) {
        statement.setInt(2, notification.getQueueId());
      } else {
        statement.setNull(2, java.sql.Types.INTEGER);
      }

      statement.setString(3, notification.getChannel());
      statement.setString(4, notification.getMessage());
      statement.setString(5, notification.getStatus());

      // sent_at
      if (notification.getSentAt() != null) {
        statement.setString(6, notification.getSentAt().toString());
      } else {
        statement.setNull(6, java.sql.Types.VARCHAR);
      }

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          notification.setNotificationId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Notification findById(int notificationId) {

    String sql =
        """
          SELECT *
          FROM notifications
          WHERE notification_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, notificationId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapNotification(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public List<Notification> findAll() {

    String sql =
        """
          SELECT *
          FROM notifications
        """;

    List<Notification> notifications = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        notifications.add(mapNotification(resultSet));
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return notifications;
  }

  public List<Notification> findByPatient(int patientId) {

    String sql =
        """
          SELECT *
          FROM notifications
          WHERE patient_id = ?
        """;

    List<Notification> notifications = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, patientId);

      try (ResultSet resultSet = statement.executeQuery()) {

        while (resultSet.next()) {
          notifications.add(mapNotification(resultSet));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return notifications;
  }

  public void update(Notification notification) {

    String sql =
        """
          UPDATE notifications
          SET patient_id = ?,
              queue_id = ?,
              channel = ?,
              message = ?,
              status = ?,
              sent_at = ?
          WHERE notification_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, notification.getPatientId());

      // queue_id
      if (notification.getQueueId() != null) {
        statement.setInt(2, notification.getQueueId());
      } else {
        statement.setNull(2, java.sql.Types.INTEGER);
      }

      statement.setString(3, notification.getChannel());
      statement.setString(4, notification.getMessage());
      statement.setString(5, notification.getStatus());

      // sent_at
      if (notification.getSentAt() != null) {
        statement.setString(6, notification.getSentAt().toString());
      } else {
        statement.setNull(6, java.sql.Types.VARCHAR);
      }

      statement.setInt(7, notification.getNotificationId());

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public void delete(int notificationId) {

    String sql =
        """
          DELETE FROM notifications
          WHERE notification_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, notificationId);

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  private Notification mapNotification(ResultSet resultSet) throws SQLException {

    Notification notification = new Notification();

    notification.setNotificationId(resultSet.getInt("notification_id"));

    notification.setPatientId(resultSet.getInt("patient_id"));

    notification.setQueueId((Integer) resultSet.getObject("queue_id"));

    notification.setChannel(resultSet.getString("channel"));

    notification.setMessage(resultSet.getString("message"));

    notification.setStatus(resultSet.getString("status"));

    String sentAt = resultSet.getString("sent_at");

    if (sentAt != null) {
      notification.setSentAt(java.time.LocalDateTime.parse(sentAt.replace(" ", "T")));
    }

    return notification;
  }
}
