package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.database.DatabaseException;
import org.hospitalqueing.model.Patient;

public class PatientDAO {

  public void save(Patient patient) {
    String sql =
        """
          INSERT INTO patients (
            user_id,
            first_name,
            last_name,
            middle_name,
            birth_date,
            sex,
            phone
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
      statement.setInt(1, patient.getUserId());
      statement.setString(2, patient.getFirstName());
      statement.setString(3, patient.getLastName());
      statement.setString(4, patient.getMiddleName());
      statement.setString(5, patient.getBirthDate());
      statement.setString(6, patient.getSex());
      statement.setString(7, patient.getPhone());

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          patient.setPatientId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }

  public Patient findById(int patientId) {

    String sql =
        """
        SELECT *
        FROM patients
        WHERE patient_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, patientId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapPatient(resultSet);
        }
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }

    return null;
  }

  public List<Patient> findAll() {
    String sql =
        """
          SELECT *
          FROM patients
          WHERE deleted_at IS NULL
        """;

    List<Patient> patients = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        patients.add(mapPatient(resultSet));
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }

    return patients;
  }

  public void update(Patient patient) {
    String sql =
        """
          UPDATE patients
          SET user_id = ?,
          first_name = ?,
          last_name = ?,
          middle_name = ?,
          birth_date = ?,
          sex = ?,
          phone = ?
        WHERE patient_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {
      statement.setInt(1, patient.getUserId());
      statement.setString(2, patient.getFirstName());
      statement.setString(3, patient.getLastName());
      statement.setString(4, patient.getMiddleName());
      statement.setString(5, patient.getBirthDate());
      statement.setString(6, patient.getSex());
      statement.setString(7, patient.getPhone());
      statement.setInt(8, patient.getPatientId());

      statement.executeUpdate();
    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }

  public void delete(int patientId) {
    String sql =
        """
          DELETE FROM patients
          WHERE patient_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {
      statement.setInt(1, patientId);

      statement.executeUpdate();
    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }

  /**
   * Returns the patient profile linked to a {@code user_id}, or {@code null} if the user has no
   * patient row. Used by the UI to translate a logged-in user (who is addressed by user id) into
   * the patient (who is addressed by patient id) before writing appointments or queue entries.
   */
  public Patient findByUserId(int userId) {
    String sql =
        """
          SELECT *
          FROM patients
          WHERE user_id = ? AND deleted_at IS NULL
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, userId);

      try (ResultSet resultSet = statement.executeQuery()) {
        if (resultSet.next()) {
          return mapPatient(resultSet);
        }
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }

    return null;
  }

  private Patient mapPatient(ResultSet resultSet) throws SQLException {

    Patient patient = new Patient();

    patient.setPatientId(resultSet.getInt("patient_id"));
    patient.setUserId(resultSet.getInt("user_id"));
    patient.setFirstName(resultSet.getString("first_name"));
    patient.setLastName(resultSet.getString("last_name"));
    patient.setMiddleName(resultSet.getString("middle_name"));
    patient.setBirthDate(resultSet.getString("birth_date"));
    patient.setSex(resultSet.getString("sex"));
    patient.setPhone(resultSet.getString("phone"));
    patient.setDeletedAt(resultSet.getString("deleted_at"));

    return patient;
  }

  /** All soft-deleted (trashed) patient rows, most recently deleted first. */
  public List<Patient> findTrashed() {
    String sql =
        """
          SELECT *
          FROM patients
          WHERE deleted_at IS NOT NULL
          ORDER BY deleted_at DESC
        """;

    List<Patient> patients = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        patients.add(mapPatient(resultSet));
      }

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }

    return patients;
  }

  /** Soft-deletes: stamps deleted_at so the row moves to the trash bin (it stays recoverable). */
  public void softDelete(int patientId) {
    String sql = """
        UPDATE patients SET deleted_at = ? WHERE patient_id = ? AND deleted_at IS NULL
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setString(1, java.time.LocalDateTime.now().withNano(0).toString());
      statement.setInt(2, patientId);

      statement.executeUpdate();

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }

  /** Restores a soft-deleted patient row back to live (clears deleted_at). */
  public void restore(int patientId) {
    String sql = """
        UPDATE patients SET deleted_at = NULL WHERE patient_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, patientId);

      statement.executeUpdate();

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }

  /** Hard delete (from the trash bin): removes the patient row for good. */
  public void permanentlyDelete(int patientId) {
    String sql =
        """
          DELETE FROM patients
          WHERE patient_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, patientId);

      statement.executeUpdate();

    } catch (SQLException e) {
      throw new DatabaseException("Database operation failed", e);
    }
  }
}
