package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.model.Payment;

public class PaymentDAO {

  public void save(Payment payment) {

    String sql =
        """
          INSERT INTO payments (
            queue_id,
            amount,
            payment_method,
            status,
            paid_at
          )
          VALUES (?, ?, ?, ?, ?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

      statement.setInt(1, payment.getQueueId());
      statement.setDouble(2, payment.getAmount());
      statement.setString(3, payment.getPaymentMethod());
      statement.setString(4, payment.getStatus());

      // paid_at
      if (payment.getPaidAt() != null) {
        statement.setString(5, payment.getPaidAt().toString());
      } else {
        statement.setNull(5, java.sql.Types.VARCHAR);
      }

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          payment.setPaymentId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Payment findById(int paymentId) {

    String sql =
        """
          SELECT *
          FROM payments
          WHERE payment_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, paymentId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapPayment(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public List<Payment> findAll() {

    String sql =
        """
          SELECT *
          FROM payments
        """;

    List<Payment> payments = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        payments.add(mapPayment(resultSet));
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return payments;
  }

  public Payment findByQueue(int queueId) {

    String sql =
        """
          SELECT *
          FROM payments
          WHERE queue_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, queueId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapPayment(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public void update(Payment payment) {

    String sql =
        """
          UPDATE payments
          SET queue_id = ?,
              amount = ?,
              payment_method = ?,
              status = ?,
              paid_at = ?
          WHERE payment_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, payment.getQueueId());
      statement.setDouble(2, payment.getAmount());
      statement.setString(3, payment.getPaymentMethod());
      statement.setString(4, payment.getStatus());

      // paid_at
      if (payment.getPaidAt() != null) {
        statement.setString(5, payment.getPaidAt().toString());
      } else {
        statement.setNull(5, java.sql.Types.VARCHAR);
      }

      statement.setInt(6, payment.getPaymentId());

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public void delete(int paymentId) {

    String sql =
        """
          DELETE FROM payments
          WHERE payment_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, paymentId);

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  private Payment mapPayment(ResultSet resultSet) throws SQLException {

    Payment payment = new Payment();

    payment.setPaymentId(resultSet.getInt("payment_id"));

    payment.setQueueId(resultSet.getInt("queue_id"));

    payment.setAmount(resultSet.getDouble("amount"));

    payment.setPaymentMethod(resultSet.getString("payment_method"));

    payment.setStatus(resultSet.getString("status"));

    String paidAt = resultSet.getString("paid_at");

    if (paidAt != null) {
      payment.setPaidAt(java.time.LocalDateTime.parse(paidAt.replace(" ", "T")));
    }

    return payment;
  }
}
