package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.model.Role;

public class RoleDAO {

  public void save(Role role) {

    String sql =
        """
          INSERT INTO roles (
            role_name
          )
          VALUES (?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

      statement.setString(1, role.getRoleName());

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          role.setRoleId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Role findById(int roleId) {

    String sql =
        """
          SELECT *
          FROM roles
          WHERE role_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, roleId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapRole(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public List<Role> findAll() {

    String sql =
        """
          SELECT *
          FROM roles
        """;

    List<Role> roles = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        roles.add(mapRole(resultSet));
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return roles;
  }

  public Role findByName(String roleName) {

    String sql =
        """
          SELECT *
          FROM roles
          WHERE role_name = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setString(1, roleName);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapRole(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public void update(Role role) {

    String sql =
        """
          UPDATE roles
          SET role_name = ?
          WHERE role_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setString(1, role.getRoleName());
      statement.setInt(2, role.getRoleId());

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public void delete(int roleId) {

    String sql =
        """
          DELETE FROM roles
          WHERE role_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, roleId);

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  private Role mapRole(ResultSet resultSet) throws SQLException {

    Role role = new Role();

    role.setRoleId(resultSet.getInt("role_id"));

    role.setRoleName(resultSet.getString("role_name"));

    return role;
  }
}
