package org.hospitalqueing.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.model.Staff;

public class StaffDAO {

  public void save(Staff staff) {

    String sql =
        """
          INSERT INTO staff (
            user_id,
            first_name,
            last_name,
            department_id
          )
          VALUES (?, ?, ?, ?)
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement =
            connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

      statement.setInt(1, staff.getUserId());
      statement.setString(2, staff.getFirstName());
      statement.setString(3, staff.getLastName());

      // department_id
      if (staff.getDepartmentId() != null) {
        statement.setInt(4, staff.getDepartmentId());
      } else {
        statement.setNull(4, java.sql.Types.INTEGER);
      }

      statement.executeUpdate();

      // Get the ID generated by SQLite
      try (ResultSet keys = statement.getGeneratedKeys()) {
        if (keys.next()) {
          staff.setStaffId(keys.getInt(1));
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public Staff findById(int staffId) {

    String sql =
        """
          SELECT *
          FROM staff
          WHERE staff_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, staffId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapStaff(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public List<Staff> findAll() {

    String sql =
        """
          SELECT *
          FROM staff
        """;

    List<Staff> staffList = new ArrayList<>();

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql);
        ResultSet resultSet = statement.executeQuery()) {

      while (resultSet.next()) {
        staffList.add(mapStaff(resultSet));
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return staffList;
  }

  public Staff findByUser(int userId) {

    String sql =
        """
          SELECT *
          FROM staff
          WHERE user_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, userId);

      try (ResultSet resultSet = statement.executeQuery()) {

        if (resultSet.next()) {
          return mapStaff(resultSet);
        }
      }

    } catch (SQLException e) {
      e.printStackTrace();
    }

    return null;
  }

  public void update(Staff staff) {

    String sql =
        """
          UPDATE staff
          SET user_id = ?,
              first_name = ?,
              last_name = ?,
              department_id = ?
          WHERE staff_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, staff.getUserId());
      statement.setString(2, staff.getFirstName());
      statement.setString(3, staff.getLastName());

      // department_id
      if (staff.getDepartmentId() != null) {
        statement.setInt(4, staff.getDepartmentId());
      } else {
        statement.setNull(4, java.sql.Types.INTEGER);
      }

      statement.setInt(5, staff.getStaffId());

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  public void delete(int staffId) {

    String sql =
        """
          DELETE FROM staff
          WHERE staff_id = ?
        """;

    try (Connection connection = DatabaseConnection.getConnection();
        PreparedStatement statement = connection.prepareStatement(sql)) {

      statement.setInt(1, staffId);

      statement.executeUpdate();

    } catch (SQLException e) {
      e.printStackTrace();
    }
  }

  private Staff mapStaff(ResultSet resultSet) throws SQLException {

    Staff staff = new Staff();

    staff.setStaffId(resultSet.getInt("staff_id"));

    staff.setUserId(resultSet.getInt("user_id"));

    staff.setFirstName(resultSet.getString("first_name"));

    staff.setLastName(resultSet.getString("last_name"));

    staff.setDepartmentId((Integer) resultSet.getObject("department_id"));

    return staff;
  }
}
