package org.hospitalqueing;

import org.hospitalqueing.database.DatabaseConnection;

/*
 * This source file was generated by the Gradle 'init' task
 */
public class Main {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    DatabaseConnection.initializeDatabase();
  }
}
