package org.hospitalqueing;

import org.hospitalqueing.database.DatabaseConnection;
import org.hospitalqueing.web.WebServer;

/*
 * This source file was generated by the Gradle 'init' task
 */
public class Main {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    DatabaseConnection.initializeDatabase();

    int port = Integer.getInteger("queue.web.port", 5000);
    new WebServer(port);
    System.out.println("Queue web API listening on http://0.0.0.0:" + port);
  }
}
