package org.hospitalqueing;

/*
 * This source file was generated by the Gradle 'init' task
 */
public class Main {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new Main().getGreeting());
  }
}
